import { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import { BarChart3, Building2, CalendarClock, Check, ChevronRight, CircleUserRound, ClipboardList, LogOut, Pencil, Plus, RefreshCw, Trash2, Users, X } from "lucide-react";
import "./styles.css";

const API_URL = import.meta.env.VITE_API_URL || "http://127.0.0.1:8000";

async function api(path, options = {}) {
  const token = localStorage.getItem("adminToken");
  const response = await fetch(`${API_URL}${path}`, {
    ...options,
    headers: { "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}), ...options.headers },
  });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data.detail || "The server could not complete that request.");
  return data;
}

const emptyEmployee = { first_name: "", last_name: "", email: "", phone: "", position: "Employee", date_joined: new Date().toISOString().slice(0, 10), password: "", department_id: "", address: "" };
const emptyDepartment = { department_name: "", description: "" };

function Login({ onLogin }) {
  const [form, setForm] = useState({ email: "", password: "" });
  const [error, setError] = useState("");
  async function submit(event) {
    event.preventDefault();
    setError("");
    try {
      const result = await api("/auth/login", { method: "POST", body: JSON.stringify(form) });
      if (!["admin", "administrator", "system administrator"].includes(result.position?.toLowerCase())) throw new Error("This account does not have administrator access.");
      localStorage.setItem("adminToken", result.access_token);
      localStorage.setItem("adminUser", JSON.stringify(result));
      onLogin(result);
    } catch (err) { setError(err.message); }
  }
  return <main className="login-shell"><div className="login-art"><span className="stamp">TT / 01</span><div><p className="kicker">WORKFORCE CONTROL</p><h1>Make every hour<br /><em>count.</em></h1><p className="art-copy">A clear command center for the people, places, and time behind your work.</p></div><span className="art-note">ADMINISTRATOR ACCESS</span></div><form className="login-card" onSubmit={submit}><div className="mark"><CalendarClock size={18} /> TIMETRACKER</div><p className="kicker">SECURE SIGN IN</p><h2>Welcome back.</h2><p className="muted">Sign in with an administrator account to continue.</p>{error && <div className="error">{error}</div>}<label>Email<input required type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></label><label>Password<input required type="password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} /></label><button className="primary full" type="submit">Enter control room <ChevronRight size={17} /></button></form></main>;
}

function Modal({ title, children, onClose }) { return <div className="modal-backdrop"><div className="modal"><div className="modal-head"><h2>{title}</h2><button className="icon-button" onClick={onClose} title="Close"><X size={18} /></button></div>{children}</div></div>; }

function AdminApp({ user, onLogout }) {
  const [tab, setTab] = useState("overview");
  const [data, setData] = useState({ employees: [], departments: [], attendance: [], summary: null });
  const [notice, setNotice] = useState("");
  const [modal, setModal] = useState(null);
  const [search, setSearch] = useState("");
  const [loading, setLoading] = useState(true);

  async function load() {
    setLoading(true);
    try { const [employees, departments, attendance, summary] = await Promise.all([api("/admin/employees"), api("/admin/departments"), api("/admin/attendance"), api("/admin/summary")]); setData({ employees, departments, attendance, summary }); setNotice(""); }
    catch (err) { setNotice(err.message); }
    finally { setLoading(false); }
  }
  useEffect(() => { load(); }, []);

  async function save(path, method, body, message) { try { await api(path, { method, body: JSON.stringify(body) }); setModal(null); setNotice(message); await load(); } catch (err) { setNotice(err.message); } }
  async function remove(path, message) { if (!window.confirm("This action cannot be undone. Continue?")) return; try { await api(path, { method: "DELETE" }); setNotice(message); await load(); } catch (err) { setNotice(err.message); } }
  const name = `${user.first_name} ${user.last_name}`;
  const filteredEmployees = data.employees.filter((item) => `${item.first_name} ${item.last_name} ${item.email} ${item.position}`.toLowerCase().includes(search.toLowerCase()));
  const departmentName = (id) => data.departments.find((item) => item.department_id === id)?.department_name || "Unassigned";
  const nav = [{ id: "overview", label: "Overview", icon: BarChart3 }, { id: "employees", label: "Employees", icon: Users }, { id: "departments", label: "Departments", icon: Building2 }, { id: "attendance", label: "Attendance", icon: ClipboardList }];
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><CalendarClock size={20} /> TIMETRACKER</div><p className="side-label">CONTROL ROOM</p><nav>{nav.map(({ id, label, icon: Icon }) => <button key={id} className={tab === id ? "nav-button active" : "nav-button"} onClick={() => setTab(id)}><Icon size={17} />{label}</button>)}</nav><div className="side-bottom"><div className="user-chip"><span className="avatar">{user.first_name[0]}{user.last_name[0]}</span><span><strong>{name}</strong><small>Administrator</small></span></div><button className="nav-button" onClick={onLogout}><LogOut size={17} />Sign out</button></div></aside><main className="content"><header className="topbar"><div><p className="kicker">WEDNESDAY / ADMINISTRATION</p><h1>{nav.find((item) => item.id === tab)?.label}</h1></div><div className="top-actions"><button className="icon-button" onClick={load} title="Refresh data"><RefreshCw size={18} /></button><div className="profile-label"><CircleUserRound size={19} /> {name}</div></div></header>{notice && <div className="notice">{notice}<button onClick={() => setNotice("")}><X size={14} /></button></div>}{loading ? <div className="loading">Loading control room...</div> : <>{tab === "overview" && <Overview data={data} onNavigate={setTab} />}{tab === "employees" && <Employees employees={filteredEmployees} departments={data.departments} search={search} setSearch={setSearch} onAdd={() => setModal({ type: "employee", value: emptyEmployee })} onEdit={(value) => setModal({ type: "employee", value: { ...value, password: "" } })} onDelete={(id) => remove(`/admin/employees/${id}`, "Employee removed.")} />}{tab === "departments" && <Departments departments={data.departments} onAdd={() => setModal({ type: "department", value: emptyDepartment })} onEdit={(value) => setModal({ type: "department", value })} onDelete={(id) => remove(`/admin/departments/${id}`, "Department removed.")} />}{tab === "attendance" && <Attendance attendance={data.attendance} employees={data.employees} onEdit={(value) => setModal({ type: "attendance", value })} />}</>}{modal?.type === "employee" && <EmployeeForm value={modal.value} departments={data.departments} onClose={() => setModal(null)} onSave={(value) => save(value.employee_id ? `/admin/employees/${value.employee_id}` : "/admin/employees", value.employee_id ? "PUT" : "POST", value, "Employee saved.")} />}{modal?.type === "department" && <DepartmentForm value={modal.value} onClose={() => setModal(null)} onSave={(value) => save(value.department_id ? `/admin/departments/${value.department_id}` : "/admin/departments", value.department_id ? "PUT" : "POST", value, "Department saved.")} />}{modal?.type === "attendance" && <AttendanceForm value={modal.value} employees={data.employees} onClose={() => setModal(null)} onSave={(value) => save(`/admin/attendance/${value.attendance_id}`, "PUT", value, "Attendance corrected.")} />}</main></div>;
}

function Overview({ data, onNavigate }) { const summary = data.summary || {}; return <><section className="hero"><div><p className="kicker">SYSTEM PULSE</p><h2>Good morning, <em>administrator.</em></h2><p className="muted">Here is the latest view of your workforce and today's attendance.</p></div><button className="primary" onClick={() => onNavigate("employees")}>Manage people <ChevronRight size={17} /></button></section><section className="metric-grid"><Metric icon={Users} label="Total employees" value={summary.employees} /><Metric icon={Building2} label="Departments" value={summary.departments} /><Metric icon={Check} label="Present today" value={summary.present_today} /><Metric icon={ClipboardList} label="Records today" value={summary.attendance_today} /></section><div className="overview-grid"><section className="panel"><div className="panel-title"><div><p className="kicker">REPORT</p><h3>Attendance breakdown</h3></div><BarChart3 size={21} /></div>{Object.entries(summary.attendance_by_status || {}).map(([status, count]) => <div className="bar-row" key={status}><span>{status}</span><div className="bar"><i style={{ width: `${Math.min(100, count / Math.max(1, data.attendance.length) * 100)}%` }} /></div><strong>{count}</strong></div>)}</section><section className="panel"><div className="panel-title"><div><p className="kicker">DIRECTORY</p><h3>Departments</h3></div><button className="text-button" onClick={() => onNavigate("departments")}>View all</button></div>{data.departments.slice(0, 5).map((department) => <div className="list-row" key={department.department_id}><span className="dot" /><span>{department.department_name}</span><ChevronRight size={15} /></div>)}</section></div></>; }
function Metric({ icon: Icon, label, value }) { return <article className="metric"><span className="metric-icon"><Icon size={19} /></span><span className="muted">{label}</span><strong>{value ?? 0}</strong></article>; }
function Employees({ employees, departments, search, setSearch, onAdd, onEdit, onDelete }) { return <section className="panel table-panel"><div className="panel-title"><div><p className="kicker">PEOPLE DIRECTORY</p><h2>Employee records</h2></div><button className="primary" onClick={onAdd}><Plus size={17} /> Add employee</button></div><input className="search" placeholder="Search by name, email, or role" value={search} onChange={(e) => setSearch(e.target.value)} /><div className="table-wrap"><table><thead><tr><th>Employee</th><th>Role</th><th>Department</th><th>Joined</th><th /></tr></thead><tbody>{employees.map((employee) => <tr key={employee.employee_id}><td><strong>{employee.first_name} {employee.last_name}</strong><small>{employee.email}</small></td><td>{employee.position}</td><td>{departments.find((item) => item.department_id === employee.department_id)?.department_name || "Unassigned"}</td><td>{employee.date_joined}</td><td className="row-actions"><button className="icon-button" onClick={() => onEdit(employee)} title="Edit employee"><Pencil size={15} /></button><button className="icon-button danger" onClick={() => onDelete(employee.employee_id)} title="Delete employee"><Trash2 size={15} /></button></td></tr>)}</tbody></table>{!employees.length && <p className="empty">No employees match this search.</p>}</div></section>; }
function Departments({ departments, onAdd, onEdit, onDelete }) { return <section className="panel table-panel"><div className="panel-title"><div><p className="kicker">ORGANIZATION</p><h2>Departments</h2></div><button className="primary" onClick={onAdd}><Plus size={17} /> Add department</button></div><div className="department-grid">{departments.map((department) => <article className="department-card" key={department.department_id}><span className="department-number">{String(department.department_id).padStart(2, "0")}</span><h3>{department.department_name}</h3><p>{department.description || "No description provided."}</p><div><button className="text-button" onClick={() => onEdit(department)}><Pencil size={14} /> Edit</button><button className="text-button danger-text" onClick={() => onDelete(department.department_id)}><Trash2 size={14} /> Delete</button></div></article>)}</div></section>; }
function Attendance({ attendance, employees, onEdit }) { return <section className="panel table-panel"><div className="panel-title"><div><p className="kicker">AUDIT LOG</p><h2>Attendance records</h2></div><span className="muted">Authorized corrections only</span></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Employee</th><th>Time in</th><th>Time out</th><th>Status</th><th /></tr></thead><tbody>{attendance.map((record) => <tr key={record.attendance_id}><td>{record.attendance_date}</td><td>{employees.find((item) => item.employee_id === record.employee_id)?.first_name || "Unknown"} {employees.find((item) => item.employee_id === record.employee_id)?.last_name || ""}</td><td>{record.time_in || "-"}</td><td>{record.time_out || "-"}</td><td><span className={`status ${record.status.toLowerCase()}`}>{record.status}</span></td><td><button className="icon-button" onClick={() => onEdit(record)} title="Correct attendance"><Pencil size={15} /></button></td></tr>)}</tbody></table>{!attendance.length && <p className="empty">No attendance records found.</p>}</div></section>; }

function EmployeeForm({ value, departments, onClose, onSave }) { const [form, setForm] = useState({ ...value, department_id: value.department_id || "" }); const update = (key, val) => setForm({ ...form, [key]: val }); return <Modal title={value.employee_id ? "Edit employee" : "Add employee"} onClose={onClose}><form className="form-grid" onSubmit={(e) => { e.preventDefault(); onSave({ ...form, department_id: Number(form.department_id) }); }}><label>First name<input required value={form.first_name} onChange={(e) => update("first_name", e.target.value)} /></label><label>Last name<input required value={form.last_name} onChange={(e) => update("last_name", e.target.value)} /></label><label>Email<input required type="email" value={form.email} onChange={(e) => update("email", e.target.value)} /></label><label>Phone<input required value={form.phone} onChange={(e) => update("phone", e.target.value)} /></label><label>Position<input required value={form.position} onChange={(e) => update("position", e.target.value)} /></label><label>Department<select required value={form.department_id} onChange={(e) => update("department_id", e.target.value)}><option value="">Select department</option>{departments.map((item) => <option key={item.department_id} value={item.department_id}>{item.department_name}</option>)}</select></label><label>Date joined<input required type="date" value={form.date_joined} onChange={(e) => update("date_joined", e.target.value)} /></label><label>Address<input required value={form.address} onChange={(e) => update("address", e.target.value)} /></label><label className="wide">Password<input required={!value.employee_id} type="password" minLength="8" value={form.password} onChange={(e) => update("password", e.target.value)} placeholder={value.employee_id ? "Enter a new password" : "Minimum 8 characters"} /></label><div className="form-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button type="submit" className="primary">Save employee</button></div></form></Modal>; }
function DepartmentForm({ value, onClose, onSave }) { const [form, setForm] = useState(value); return <Modal title={value.department_id ? "Edit department" : "Add department"} onClose={onClose}><form className="form-grid one-column" onSubmit={(e) => { e.preventDefault(); onSave(form); }}><label>Department name<input required value={form.department_name} onChange={(e) => setForm({ ...form, department_name: e.target.value })} /></label><label>Description<textarea rows="4" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label><div className="form-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button type="submit" className="primary">Save department</button></div></form></Modal>; }
function AttendanceForm({ value, employees, onClose, onSave }) { const [form, setForm] = useState(value); return <Modal title="Correct attendance" onClose={onClose}><form className="form-grid" onSubmit={(e) => { e.preventDefault(); onSave({ ...form, employee_id: Number(form.employee_id) }); }}><label>Employee<select required value={form.employee_id} onChange={(e) => setForm({ ...form, employee_id: e.target.value })}>{employees.map((item) => <option key={item.employee_id} value={item.employee_id}>{item.first_name} {item.last_name}</option>)}</select></label><label>Date<input required type="date" value={form.attendance_date} onChange={(e) => setForm({ ...form, attendance_date: e.target.value })} /></label><label>Time in<input type="time" value={form.time_in || ""} onChange={(e) => setForm({ ...form, time_in: e.target.value || null })} /></label><label>Time out<input type="time" value={form.time_out || ""} onChange={(e) => setForm({ ...form, time_out: e.target.value || null })} /></label><label>Status<select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })}><option>Present</option><option>Absent</option><option>Late</option><option>Leave</option></select></label><div className="form-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button type="submit" className="primary">Save correction</button></div></form></Modal>; }

function App() { const [user, setUser] = useState(() => JSON.parse(localStorage.getItem("adminUser") || "null")); if (!user) return <Login onLogin={setUser} />; return <AdminApp user={user} onLogout={() => { localStorage.removeItem("adminToken"); localStorage.removeItem("adminUser"); setUser(null); }} />; }

export default App;

createRoot(document.getElementById("root")).render(<App />);